/** @externs */
// Generated by gcc-ts-bundler for: vue
// Mode: runtime-aware
// Scanned 11 type files and 7 runtime files.

Object.prototype.__v_isRef;
Object.prototype.__v_isShallow;
Object.prototype.__v_skip;
Object.prototype._value;
Object.prototype.$evtclick;
Object.prototype.clickCount;
Object.prototype.default;
Object.prototype.key;
Object.prototype.pause;
Object.prototype.resume;
Object.prototype.source;
Object.prototype.stop;
Object.prototype.value;
