import fs from "fs/promises";
import path from "path";
import * as closureCompilerPackage from "google-closure-compiler";
// @ts-expect-error - package does not expose types for this internal helper.
import { getNativeImagePath } from "google-closure-compiler/lib/utils.js";

import { copyOrLinkFiles } from "../../internal/file-state";
import {
  ChunkPlanChunk,
  LazyImport,
  NormalizedBuildOptions,
} from "../../internal/types";
import { rewriteGccExports } from "../../native/load";

type ClosureCompilerClass = (typeof closureCompilerPackage)["compiler"] & {
  JAR_PATH?: unknown;
};

type ClosureCompilerInstance = InstanceType<ClosureCompilerClass> & {
  JAR_PATH?: null | string;
  javaPath?: string;
};

type ClosureCompilerPackageShape = typeof closureCompilerPackage & {
  JAR_PATH?: unknown;
};
type ClosureCompilerOptions = ConstructorParameters<ClosureCompilerClass>[0];

interface ClosureChunk {
  dependencies: string[];
  entryPoints: string[];
  files: string[];
  kind?: ChunkPlanChunk["kind"];
  lazyModuleIds: string[];
  name: string;
}

interface ChunkBridgeFile {
  chunkName: string;
  filePath: string;
  moduleId: string;
  preloadBindingName: string;
  runtimeBindingName: string;
}

export interface ClosureStageResult {
  cacheOutputFiles: string[];
  exitCode: number;
  outputFiles: string[];
}

const closureLibFilesCache = new Map<string, Promise<string[]>>();
const CHUNK_NAMESPACE = "__gcc$chunks";
const CHUNK_MANAGER_JUSTIFICATION =
  "Generated by gcc-ts-bundler chunk runtime.";
const BUNDLER_RUNTIME_GLOBAL = "__gcc_runtime__";

export async function runClosureStage({
  chunkPlan,
  emittedOutDir,
  externPaths,
  finalCacheDir,
  options,
  outDir,
  supportFiles,
  lazyImports,
  packageRoot,
}: {
  chunkPlan: ChunkPlanChunk[];
  emittedOutDir: string;
  externPaths: string[];
  finalCacheDir: string;
  lazyImports: LazyImport[];
  options: NormalizedBuildOptions;
  outDir: string;
  supportFiles: string[];
  packageRoot: string;
}): Promise<ClosureStageResult> {
  await fs.rm(finalCacheDir, { force: true, recursive: true });
  await fs.mkdir(finalCacheDir, { recursive: true });

  const rawDir = path.join(finalCacheDir, "raw");
  const cacheOutputDir = path.join(finalCacheDir, "outputs");
  const supportDir = path.join(emittedOutDir, "__gcc_chunk_support");
  await fs.mkdir(rawDir, { recursive: true });
  await fs.mkdir(cacheOutputDir, { recursive: true });
  await fs.rm(supportDir, { force: true, recursive: true });
  await fs.mkdir(supportDir, { recursive: true });
  await fs.rm(outDir, { force: true, recursive: true });
  await fs.mkdir(outDir, { recursive: true });

  const resolvedChunks = resolveChunkPlan(chunkPlan, emittedOutDir);
  let finalSupportFiles = [...supportFiles];
  let manifestOutputPath: string | null = null;
  let runtimeEntryPoint: string | null = null;

  if (options.chunks.mode === "bundler-runtime") {
    const bundlerAssets = await createBundlerRuntimeAssets({
      chunkPlan: resolvedChunks,
      emittedOutDir,
      finalCacheDir,
      options,
    });
    manifestOutputPath = bundlerAssets.manifestOutputPath;
    const exitCode = await runBundlerRuntimeCompilation({
      chunkPlan: resolvedChunks,
      chunkSources: bundlerAssets.chunkSources,
      externPaths: [...externPaths, bundlerAssets.runtimeExternsPath],
      options,
      outputDir: rawDir,
      packageRoot,
    });
    if (exitCode !== 0) {
      return { cacheOutputFiles: [], exitCode, outputFiles: [] };
    }

    const outputFiles = resolvedChunks.map((chunk) =>
      path.join(outDir, `${chunk.name}.js`),
    );
    await Promise.all(
      outputFiles.map((outputFile, index) =>
        fs.copyFile(path.join(rawDir, `${resolvedChunks[index].name}.js`), outputFile),
      ),
    );

    const publishedFiles =
      manifestOutputPath === null ? outputFiles : [...outputFiles, manifestOutputPath];
    await copyOrLinkFiles(publishedFiles, cacheOutputDir);
    const cacheOutputFiles = publishedFiles.map((outputFile) =>
      path.join(cacheOutputDir, path.relative(outDir, outputFile)),
    );

    return { cacheOutputFiles, exitCode: 0, outputFiles: publishedFiles };
  }

  if (options.chunks.mode === "closure-library") {
    const chunkAssets = await createChunkRuntimeAssets({
      chunkPlan: resolvedChunks,
      emittedOutDir,
      lazyImports,
      options,
      supportDir,
    });
    finalSupportFiles = uniquePaths([
      ...supportFiles,
      chunkAssets.runtimeSupportFile,
    ]);
    runtimeEntryPoint = chunkAssets.runtimeModuleId;
    applyChunkBridgesToResolvedChunks(resolvedChunks, chunkAssets.bridgeFiles);
    if (options.chunks.manifestFile) {
      manifestOutputPath = path.join(outDir, options.chunks.manifestFile);
      await fs.mkdir(path.dirname(manifestOutputPath), { recursive: true });
      await fs.writeFile(manifestOutputPath, chunkAssets.manifestText, "utf-8");
      await fs.mkdir(
        path.join(cacheOutputDir, path.dirname(options.chunks.manifestFile)),
        {
          recursive: true,
        },
      );
      await fs.writeFile(
        path.join(cacheOutputDir, options.chunks.manifestFile),
        chunkAssets.manifestText,
        "utf-8",
      );
    }
  }
  const closureLibFiles = await collectClosureLibFiles(packageRoot, [
    ...finalSupportFiles,
    ...resolvedChunks.flatMap((chunk) => chunk.files),
  ]);

  const exitCode =
    resolvedChunks.length === 1 && options.chunks.mode !== "closure-library"
      ? await runSingleClosureCompilation({
          closureLibFiles,
          entryChunk: resolvedChunks[0],
          externPaths,
          options,
          supportFiles: finalSupportFiles,
          rawOutputPath: path.join(rawDir, `${resolvedChunks[0].name}.js`),
        })
      : await runChunkedClosureCompilation({
          chunkPlan: resolvedChunks,
          closureLibFiles,
          externPaths,
          options,
          outputDir: rawDir,
          runtimeEntryPoint,
          supportFiles: finalSupportFiles,
          wrapperNamespace: toChunkWrapperNamespace(
            options.chunks.baseChunkName || resolvedChunks[0]?.name || "main",
          ),
        });

  if (exitCode !== 0) {
    return { cacheOutputFiles: [], exitCode, outputFiles: [] };
  }

  const rawOutputs = resolvedChunks.map((chunk) =>
    path.join(rawDir, `${chunk.name}.js`),
  );
  const outputFiles = resolvedChunks.map((chunk) =>
    path.join(outDir, `${chunk.name}.js`),
  );
  if (options.chunks.mode === "closure-library") {
    await Promise.all(
      rawOutputs.map(async (rawFile, index) => {
        const contents = await fs.readFile(rawFile, "utf-8");
        await fs.writeFile(outputFiles[index], contents);
      }),
    );
  } else {
    await Promise.all(
      rawOutputs.map(async (rawFile, index) => {
        const contents = await fs.readFile(rawFile, "utf-8");
        const transformed = rewriteGccExports(contents);
        await fs.writeFile(outputFiles[index], transformed);
      }),
    );
  }

  const publishedFiles =
    manifestOutputPath === null ? outputFiles : [...outputFiles, manifestOutputPath];
  await copyOrLinkFiles(publishedFiles, cacheOutputDir);
  const cacheOutputFiles = publishedFiles.map((outputFile) =>
    path.join(
      cacheOutputDir,
      path.relative(outDir, outputFile),
    ),
  );

  return { cacheOutputFiles, exitCode: 0, outputFiles: publishedFiles };
}

async function runSingleClosureCompilation({
  closureLibFiles,
  entryChunk,
  externPaths,
  options,
  supportFiles,
  rawOutputPath,
}: {
  closureLibFiles: string[];
  entryChunk: ClosureChunk;
  externPaths: string[];
  options: NormalizedBuildOptions;
  supportFiles: string[];
  rawOutputPath: string;
}) {
  const closureOptions: ClosureCompilerOptions = {
    assumeFunctionWrapper: true,
    compilationLevel: options.compilationLevel,
    dependencyMode: "PRUNE",
    externs: uniquePaths(externPaths),
    js: uniquePaths([
      ...options.js,
      ...closureLibFiles,
      ...supportFiles,
      ...entryChunk.files,
    ]),
    jsOutputFile: rawOutputPath,
    languageIn: "UNSTABLE",
    languageOut: options.languageOut,
    rewritePolyfills: false,
    warningLevel: options.diagnostics.verbose ? "VERBOSE" : "QUIET",
  };
  if (entryChunk.entryPoints.length > 0) {
    closureOptions.entryPoint = entryChunk.entryPoints;
  }
  applyInternalClosureDebugOptions(closureOptions);
  return runClosureCompiler(closureOptions);
}

async function runChunkedClosureCompilation({
  chunkPlan,
  closureLibFiles,
  externPaths,
  options,
  outputDir,
  runtimeEntryPoint,
  supportFiles,
  wrapperNamespace,
}: {
  chunkPlan: ClosureChunk[];
  closureLibFiles: string[];
  externPaths: string[];
  options: NormalizedBuildOptions;
  outputDir: string;
  runtimeEntryPoint: null | string;
  supportFiles: string[];
  wrapperNamespace: string;
}) {
  const leadingJs = uniquePaths([
    ...options.js,
    ...closureLibFiles,
    ...supportFiles,
  ]);
  const chunkSpecs = chunkPlan.map((chunk, index) => {
    const dependencySuffix =
      chunk.dependencies.length > 0 ? `:${chunk.dependencies.join(",")}` : "";
    return `${chunk.name}:${uniquePaths(chunk.files).length + (index === 0 ? leadingJs.length : 0)}${dependencySuffix}`;
  });
  const chunkFiles = uniquePaths([
    ...leadingJs,
    ...chunkPlan.flatMap((chunk) => chunk.files),
  ]);

  const closureOptions: ClosureCompilerOptions = {
    assumeFunctionWrapper: true,
    compilationLevel: options.compilationLevel,
    chunk: chunkSpecs,
    chunkOutputPathPrefix: `${outputDir}${path.sep}`,
    dependencyMode: "PRUNE",
    externs: uniquePaths(externPaths),
    js: chunkFiles,
    languageIn: "UNSTABLE",
    languageOut: options.languageOut,
    rewritePolyfills: false,
    warningLevel: options.diagnostics.verbose ? "VERBOSE" : "QUIET",
  };
  const entryPoints = uniquePaths(
    [
      ...(runtimeEntryPoint ? [runtimeEntryPoint] : []),
      ...chunkPlan.flatMap((chunk) => chunk.entryPoints),
    ],
  );
  if (entryPoints.length > 0) {
    closureOptions.entryPoint = entryPoints;
  }
  if (options.chunks.mode === "closure-library") {
    const mutableOptions = closureOptions as ClosureCompilerOptions & {
      chunkOutputType?: string;
      chunkWrapper?: string[];
      renamePrefixNamespace?: string;
    };
    mutableOptions.chunkOutputType = "GLOBAL_NAMESPACE";
    mutableOptions.renamePrefixNamespace = CHUNK_NAMESPACE;
    mutableOptions.chunkWrapper = chunkPlan.map(
      (chunk) => `${chunk.name}:${createChunkWrapper(chunk, wrapperNamespace)}`,
    );
  }
  applyInternalClosureDebugOptions(closureOptions);
  return runClosureCompiler(closureOptions);
}

function applyInternalClosureDebugOptions(
  closureOptions: ClosureCompilerOptions,
) {
  const mutableOptions = closureOptions as ClosureCompilerOptions & {
    debug?: boolean;
    formatting?: string;
    useTypesForOptimization?: boolean;
  };
  if (process.env.GCC_CLOSURE_DEBUG === "1") {
    mutableOptions.debug = true;
    mutableOptions.formatting = "PRETTY_PRINT";
  }
  if (process.env.GCC_USE_TYPES_FOR_OPTIMIZATION === "false") {
    mutableOptions.useTypesForOptimization = false;
  }
}

async function createBundlerRuntimeAssets({
  chunkPlan,
  emittedOutDir,
  finalCacheDir,
  options,
}: {
  chunkPlan: ClosureChunk[];
  emittedOutDir: string;
  finalCacheDir: string;
  options: NormalizedBuildOptions;
}) {
  const assetDir = path.join(finalCacheDir, "bundler-runtime");
  await fs.rm(assetDir, { force: true, recursive: true });
  await fs.mkdir(assetDir, { recursive: true });

  const baseChunk = chunkPlan.find((chunk) => chunk.kind === "base") ?? chunkPlan[0];
  const moduleMap = Object.fromEntries(
    chunkPlan.flatMap((chunk) =>
      chunk.files.map((filePath) => [
        toGoogModuleId(filePath, emittedOutDir),
        chunk.name,
      ]),
    ),
  );
  const chunkManifest = Object.fromEntries(
    chunkPlan.map((chunk) => [
      chunk.name,
      {
        deps: chunk.dependencies,
        modules: chunk.files.map((filePath) => toGoogModuleId(filePath, emittedOutDir)),
        url: `${options.chunks.publicPath}${chunk.name}.js`,
      },
    ]),
  );
  const manifest = {
    baseChunk: baseChunk.name,
    chunks: chunkManifest,
    loader: options.chunks.loader,
    modules: moduleMap,
    publicPath: options.chunks.publicPath,
  };
  const runtimeExternsPath = path.join(assetDir, "runtime.externs.js");
  const exportNames = new Set<string>();

  const chunkSources = await Promise.all(
    chunkPlan.map(async (chunk) => {
      const moduleSources = await Promise.all(
        chunk.files.map((filePath) => fs.readFile(filePath, "utf-8")),
      );
      for (const sourceText of moduleSources) {
        for (const exportName of collectBundlerRuntimeExportNames(sourceText)) {
          exportNames.add(exportName);
        }
      }
      const moduleText = moduleSources.join("\n");
      const sourceText =
        chunk.name === baseChunk.name
          ? renderBundlerRuntimeBaseChunk({
              chunkId: chunk.name,
              entryPoints: chunk.entryPoints,
              loader: options.chunks.loader,
              manifest,
              moduleText,
            })
          : renderBundlerRuntimeLazyChunk({
              chunkId: chunk.name,
              moduleText,
            });
      const sourcePath = path.join(assetDir, `${chunk.name}.linked.js`);
      await fs.writeFile(sourcePath, sourceText, "utf-8");
      return { chunkName: chunk.name, sourcePath };
    }),
  );
  await fs.writeFile(
    runtimeExternsPath,
    renderBundlerRuntimeExterns(exportNames),
    "utf-8",
  );

  const manifestOutputPath = options.chunks.manifestFile
    ? path.join(options.outDir, options.chunks.manifestFile)
    : null;
  if (manifestOutputPath) {
    await fs.mkdir(path.dirname(manifestOutputPath), { recursive: true });
    await fs.writeFile(
      manifestOutputPath,
      `${JSON.stringify(manifest, null, 2)}\n`,
      "utf-8",
    );
  }

  return {
    chunkSources,
    manifestOutputPath,
    runtimeExternsPath,
  };
}

async function runBundlerRuntimeCompilation({
  chunkPlan,
  chunkSources,
  externPaths,
  options,
  outputDir,
  packageRoot,
}: {
  chunkPlan: ClosureChunk[];
  chunkSources: Array<{ chunkName: string; sourcePath: string }>;
  externPaths: string[];
  options: NormalizedBuildOptions;
  outputDir: string;
  packageRoot: string;
}) {
  for (const chunk of chunkPlan) {
    const chunkSource = chunkSources.find(
      (candidate) => candidate.chunkName === chunk.name,
    );
    if (!chunkSource) {
      throw new Error(`Missing linked chunk source for ${chunk.name}`);
    }
    const extraJs = chunk.kind === "base" ? options.js : [];
    const closureLibFiles = await collectClosureLibFiles(packageRoot, [
      ...extraJs,
      chunkSource.sourcePath,
    ]);
    const closureOptions: ClosureCompilerOptions = {
      assumeFunctionWrapper: true,
      compilationLevel: options.compilationLevel,
      externs: uniquePaths(externPaths),
      js: uniquePaths([...extraJs, ...closureLibFiles, chunkSource.sourcePath]),
      jsOutputFile: path.join(outputDir, `${chunk.name}.js`),
      languageIn: "UNSTABLE",
      languageOut: options.languageOut,
      rewritePolyfills: false,
      warningLevel: options.diagnostics.verbose ? "VERBOSE" : "QUIET",
    };
    applyInternalClosureDebugOptions(closureOptions);
    const exitCode = await runClosureCompiler(closureOptions);
    if (exitCode !== 0) {
      return exitCode;
    }
  }
  return 0;
}

function renderBundlerRuntimeExterns(exportNames: Set<string>) {
  const lines = [
    "/** @externs */",
    `Window.prototype.${BUNDLER_RUNTIME_GLOBAL};`,
    `WorkerGlobalScope.prototype.${BUNDLER_RUNTIME_GLOBAL};`,
    "Object.prototype.markChunkFailed;",
    "Object.prototype.markChunkLoaded;",
    "Object.prototype.preloadDynamicImport;",
    "Object.prototype.registerModule;",
    "Object.prototype.require;",
    "Object.prototype.runEntries;",
    "",
  ];
  for (const exportName of [...exportNames].sort((left, right) =>
    left.localeCompare(right),
  )) {
    lines.push(
      /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(exportName)
        ? `Object.prototype.${exportName};`
        : `Object.prototype[${JSON.stringify(exportName)}];`,
    );
  }
  lines.push("");
  return lines.join("\n");
}

function collectBundlerRuntimeExportNames(sourceText: string) {
  const exportNames = new Set<string>();
  for (const match of sourceText.matchAll(/__exports\[(["'])(.+?)\1\]\s*=/g)) {
    exportNames.add(match[2]);
  }
  return exportNames;
}

function renderBundlerRuntimeBaseChunk({
  chunkId,
  entryPoints,
  loader,
  manifest,
  moduleText,
}: {
  chunkId: string;
  entryPoints: string[];
  loader: string;
  manifest: Record<string, unknown>;
  moduleText: string;
}) {
  return [
    renderBundlerRuntimePreamble({
      loader,
      manifest: JSON.stringify(manifest),
    }),
    moduleText,
    `globalThis[${JSON.stringify(BUNDLER_RUNTIME_GLOBAL)}]["markChunkLoaded"](${JSON.stringify(
      chunkId,
    )});`,
    `globalThis[${JSON.stringify(BUNDLER_RUNTIME_GLOBAL)}]["runEntries"](${JSON.stringify(
      entryPoints,
    )});`,
    "",
  ].join("\n");
}

function renderBundlerRuntimeLazyChunk({
  chunkId,
  moduleText,
}: {
  chunkId: string;
  moduleText: string;
}) {
  return [
    "(function(__gcc_runtime){",
    'if(!__gcc_runtime)throw new Error("bundler-runtime base chunk must load before lazy chunks.");',
    moduleText,
    `__gcc_runtime["markChunkLoaded"](${JSON.stringify(chunkId)});`,
    `}).call(this,globalThis[${JSON.stringify(BUNDLER_RUNTIME_GLOBAL)}]);`,
    "",
  ].join("\n");
}

function renderBundlerRuntimePreamble({
  loader,
  manifest,
}: {
  loader: string;
  manifest: string;
}) {
  return [
    "(function(global){",
    `var runtimeKey=${JSON.stringify(BUNDLER_RUNTIME_GLOBAL)};`,
    "var runtime=global[runtimeKey]||(global[runtimeKey]={});",
    "if(!runtime[\"initialized\"]){",
    "runtime[\"manifest\"]=null;",
    "runtime[\"factories\"]=Object.create(null);",
    "runtime[\"cache\"]=Object.create(null);",
    "runtime[\"chunkStates\"]=Object.create(null);",
    "runtime[\"chunkDeferreds\"]=Object.create(null);",
    "runtime[\"baseUrl\"]=\"\";",
    "runtime[\"loaderMode\"]=\"auto\";",
    "runtime[\"resolveChunkUrl\"]=function(chunkId){var manifest=runtime[\"manifest\"];var chunk=manifest&&manifest[\"chunks\"]&&manifest[\"chunks\"][chunkId];if(!chunk)throw new Error(\"Unknown chunk \" + chunkId);return new URL(chunk[\"url\"], runtime[\"baseUrl\"] || (global.location && global.location.href ? global.location.href : \"./\")).toString();};",
    "runtime[\"getDeferred\"]=function(chunkId){var existing=runtime[\"chunkDeferreds\"][chunkId];if(existing)return existing;var deferred={};deferred[\"promise\"]=new Promise(function(resolve,reject){deferred[\"resolve\"]=resolve;deferred[\"reject\"]=reject;});runtime[\"chunkDeferreds\"][chunkId]=deferred;return deferred;};",
    "runtime[\"markChunkLoaded\"]=function(chunkId){runtime[\"chunkStates\"][chunkId]=\"loaded\";var deferred=runtime[\"chunkDeferreds\"][chunkId];if(deferred){deferred[\"resolve\"]();delete runtime[\"chunkDeferreds\"][chunkId];}};",
    "runtime[\"markChunkFailed\"]=function(chunkId,error){runtime[\"chunkStates\"][chunkId]=\"failed\";var deferred=runtime[\"chunkDeferreds\"][chunkId];if(deferred){deferred[\"reject\"](error);delete runtime[\"chunkDeferreds\"][chunkId];}};",
    "runtime[\"registerModule\"]=function(moduleId,_deps,factory){runtime[\"factories\"][moduleId]=factory;};",
    "runtime[\"require\"]=function(moduleId){if(Object.prototype.hasOwnProperty.call(runtime[\"cache\"],moduleId))return runtime[\"cache\"][moduleId];var factory=runtime[\"factories\"][moduleId];if(!factory)throw new Error(\"Module not registered: \" + moduleId);var exports={};runtime[\"cache\"][moduleId]=exports;factory(runtime[\"require\"], exports, runtime[\"dynamicImport\"], runtime[\"preloadDynamicImport\"]);return exports;};",
    "runtime[\"loadWithScript\"]=function(chunkId,url){return new Promise(function(resolve,reject){var script=global.document.createElement(\"script\");script.async=true;script.src=url;script.onload=function(){resolve();};script.onerror=function(){reject(new Error(\"Failed to load chunk \" + chunkId));};(global.document.head||global.document.documentElement).appendChild(script);});};",
    "runtime[\"loadWithFetch\"]=function(chunkId,url){return Promise.resolve(global.fetch(url)).then(function(response){if(!response.ok)throw new Error(\"Failed to fetch chunk \" + chunkId + \" (\" + response.status + \")\");return response.text();}).then(function(source){(0, global.eval)(source + \"\\n//# sourceURL=\" + url);});};",
    "runtime[\"selectLoader\"]=function(){if(runtime[\"loaderMode\"]!==\"auto\")return runtime[\"loaderMode\"];return global.document ? \"script\" : \"fetch\";};",
    "runtime[\"ensureChunk\"]=function(chunkId){var state=runtime[\"chunkStates\"][chunkId];if(state===\"loaded\")return Promise.resolve();if(state===\"loading\"){return runtime[\"getDeferred\"](chunkId)[\"promise\"];}var manifest=runtime[\"manifest\"];var chunk=manifest&&manifest[\"chunks\"]&&manifest[\"chunks\"][chunkId];if(!chunk)throw new Error(\"Unknown chunk \" + chunkId);runtime[\"chunkStates\"][chunkId]=\"loading\";var deferred=runtime[\"getDeferred\"](chunkId);var loader=runtime[\"selectLoader\"]();return Promise.all((chunk[\"deps\"]||[]).map(function(depId){return runtime[\"ensureChunk\"](depId);})).then(function(){var url=runtime[\"resolveChunkUrl\"](chunkId);return loader===\"fetch\"?runtime[\"loadWithFetch\"](chunkId,url):runtime[\"loadWithScript\"](chunkId,url);}).then(function(){return deferred[\"promise\"];}).catch(function(error){runtime[\"markChunkFailed\"](chunkId,error);throw error;});};",
    "runtime[\"dynamicImport\"]=function(moduleId){var manifest=runtime[\"manifest\"];var chunkId=manifest&&manifest[\"modules\"]&&manifest[\"modules\"][moduleId];if(!chunkId)throw new Error(\"Unknown module \" + moduleId);return runtime[\"ensureChunk\"](chunkId).then(function(){return runtime[\"require\"](moduleId);});};",
    "runtime[\"preloadDynamicImport\"]=function(moduleId){var manifest=runtime[\"manifest\"];var chunkId=manifest&&manifest[\"modules\"]&&manifest[\"modules\"][moduleId];if(!chunkId)throw new Error(\"Unknown module \" + moduleId);return runtime[\"ensureChunk\"](chunkId).then(function(){});};",
    "runtime[\"runEntries\"]=function(entryIds){for(var index=0;index<entryIds.length;index+=1)runtime[\"require\"](entryIds[index]);};",
    "runtime[\"init\"]=function(manifest, loaderMode){runtime[\"manifest\"]=manifest;runtime[\"loaderMode\"]=loaderMode||runtime[\"loaderMode\"];var currentScript=global.document&&global.document.currentScript&&global.document.currentScript.src?global.document.currentScript.src:(global.location&&global.location.href?global.location.href:\"./\");runtime[\"baseUrl\"]=new URL(manifest[\"publicPath\"]||\"./\", currentScript).toString();runtime[\"chunkStates\"][manifest[\"baseChunk\"]]=\"loaded\";};",
    "runtime[\"initialized\"]=true;",
    "}",
    `runtime["init"](${manifest}, ${JSON.stringify(loader)});`,
    "}).call(this,globalThis);",
    "",
  ].join("\n");
}

async function createChunkRuntimeAssets({
  chunkPlan,
  emittedOutDir,
  lazyImports,
  options,
  supportDir,
}: {
  chunkPlan: ClosureChunk[];
  emittedOutDir: string;
  lazyImports: LazyImport[];
  options: NormalizedBuildOptions;
  supportDir: string;
}) {
  const baseChunk = chunkPlan.find((chunk) => chunk.kind === "base") ?? chunkPlan[0];
  const chunkUrls = chunkPlan.map(
    (chunk) => `${options.chunks.publicPath}${chunk.name}.js`,
  );
  const uniqueLazyImports = dedupeLazyImports(lazyImports);
  const bridgeFiles = await Promise.all(
    uniqueLazyImports.map(async (lazyImport: LazyImport, index: number) => {
      const chunkName = chunkPlan.find((chunk) =>
        chunk.lazyModuleIds.includes(lazyImport.moduleId),
      )?.name;
      if (!chunkName) {
        throw new Error(`Missing lazy chunk for ${lazyImport.moduleId}`);
      }
      const filePath = path.join(supportDir, `lazy-bridge-${index}.js`);
      const moduleId = toGoogModuleId(filePath, emittedOutDir);
      await fs.writeFile(
        filePath,
        renderLazyBridgeModule(moduleId, lazyImport.moduleId),
        "utf-8",
      );
      return {
        chunkName,
        filePath,
        moduleId,
        preloadBindingName: lazyImport.preloadBindingName ?? `__gcc_preload_${index}`,
        runtimeBindingName: lazyImport.runtimeBindingName ?? `__gcc_lazy_${index}`,
      };
    }),
  );
  const manifest = {
    baseChunkName: baseChunk.name,
    chunkDependencies: Object.fromEntries(
      chunkPlan.map((chunk) => [chunk.name, chunk.dependencies]),
    ),
    chunkUrls: Object.fromEntries(
      chunkPlan.map((chunk) => [
        chunk.name,
        `${options.chunks.publicPath}${chunk.name}.js`,
      ]),
    ),
    lazyModules: Object.fromEntries(
      uniqueLazyImports.map((lazyImport: LazyImport) => [
        lazyImport.moduleId,
        chunkPlan.find((chunk) => chunk.lazyModuleIds.includes(lazyImport.moduleId))
          ?.name ?? "",
      ]),
    ),
    namespace: CHUNK_NAMESPACE,
    publicPath: options.chunks.publicPath,
  };
  const runtimeSupportFile = path.join(supportDir, "runtime.js");
  await fs.writeFile(
    runtimeSupportFile,
    renderChunkRuntimeSupport({
      bridgeFiles,
      chunkNames: chunkPlan.map((chunk) => chunk.name),
      chunkUrls,
      publicPath: options.chunks.publicPath,
      moduleInfoString: renderModuleInfoString(chunkPlan),
    }),
    "utf-8",
  );
  return {
    bridgeFiles,
    manifestText: `${JSON.stringify(manifest, null, 2)}\n`,
    runtimeModuleId: "gcc.__gcc_chunk_runtime",
    runtimeSupportFile,
  };
}

function renderChunkRuntimeSupport({
  bridgeFiles,
  chunkNames,
  chunkUrls,
  publicPath,
  moduleInfoString,
}: {
  bridgeFiles: Array<{
    chunkName: string;
    filePath: string;
    moduleId: string;
    preloadBindingName: string;
    runtimeBindingName: string;
  }>;
  chunkNames: string[];
  chunkUrls: string[];
  publicPath: string;
  moduleInfoString: string;
}) {
  const chunkUrlMap = Object.fromEntries(
    chunkNames.map((chunkName, index) => [chunkName, chunkUrls[index] ?? ""]),
  );
  return [
    'goog.module("gcc.__gcc_chunk_runtime");',
    'const googModule = goog.require("goog.module");',
    'const ModuleLoader = goog.require("goog.module.ModuleLoader");',
    'const ModuleManager = goog.require("goog.module.ModuleManager");',
    'const uncheckedConversions = goog.require("goog.html.uncheckedconversions");',
    'const Const = goog.require("goog.string.Const");',
    `const __gcc_chunk_urls = ${JSON.stringify(chunkUrlMap)};`,
    `const __gcc_module_info = ${JSON.stringify(moduleInfoString)};`,
    `const __gcc_public_path = ${JSON.stringify(publicPath)};`,
    `const __gcc_justification = Const.from(${JSON.stringify(
      CHUNK_MANAGER_JUSTIFICATION,
    )});`,
    "const __gcc_loader = new ModuleLoader();",
    "__gcc_loader.setUseScriptTags(true);",
    "const __gcc_manager = ModuleManager.getInstance();",
    "__gcc_manager.setLoader(__gcc_loader);",
    "__gcc_manager.setBatchModeEnabled(false);",
    "__gcc_manager.setConcurrentLoadingEnabled(false);",
    "__gcc_manager.setAllModuleInfoString(__gcc_module_info);",
    "__gcc_manager.setModuleTrustedUris((function() {",
    "  const baseUrl = document.currentScript && document.currentScript.src ? new URL(__gcc_public_path, document.currentScript.src).toString() : __gcc_public_path;",
    "  const trustedUris = {};",
    "  for (const chunkId in __gcc_chunk_urls) {",
    "    trustedUris[chunkId] = [uncheckedConversions.trustedResourceUrlFromStringKnownToSatisfyTypeContract(__gcc_justification, new URL(__gcc_chunk_urls[chunkId], baseUrl).toString())];",
    "  }",
    "  return trustedUris;",
    "})());",
    "__gcc_manager.setModuleContext(globalThis);",
    "const __gcc_module_cache = new Map();",
    "function __gcc_wrap_module(moduleId) {",
    "  if (__gcc_module_cache.has(moduleId)) {",
    "    return __gcc_module_cache.get(moduleId);",
    "  }",
    "  const target = googModule.get(moduleId);",
    "  const wrapped = new Proxy(target, {",
    "    get(moduleTarget, property, receiver) {",
    "      if (property === 'm') {",
    "        return function(exportName) {",
    "          if (!Object.prototype.hasOwnProperty.call(moduleTarget, exportName)) {",
    "            throw new Error('Missing export \"' + exportName + '\" from lazy module ' + moduleId);",
    "          }",
    "          return moduleTarget[exportName];",
    "        };",
    "      }",
    "      if (typeof property === 'string' && !Reflect.has(moduleTarget, property)) {",
    "        throw new Error('Missing property \"' + property + '\" from lazy module ' + moduleId);",
    "      }",
    "      return Reflect.get(moduleTarget, property, receiver);",
    "    },",
    "    has(moduleTarget, property) {",
    "      return property === 'm' || Reflect.has(moduleTarget, property);",
    "    },",
    "  });",
    "  __gcc_module_cache.set(moduleId, wrapped);",
    "  return wrapped;",
    "}",
    "function __gcc_load(chunkId, moduleId) {",
    "  return Promise.resolve(__gcc_manager.load(chunkId)).then(function() {",
    "    return __gcc_wrap_module(moduleId);",
    "  });",
    "}",
    "function __gcc_preload(chunkId) {",
    "  return Promise.resolve(__gcc_manager.preloadModule(chunkId)).then(function() {});",
    "}",
    ...bridgeFiles.flatMap((bridge) => {
      return [
        `function ${bridge.runtimeBindingName}() { return __gcc_load(${JSON.stringify(
          bridge.chunkName,
        )}, ${JSON.stringify(bridge.moduleId)}); }`,
        `function ${bridge.preloadBindingName}() { return __gcc_preload(${JSON.stringify(
          bridge.chunkName,
        )}); }`,
        `exports.${bridge.runtimeBindingName} = ${bridge.runtimeBindingName};`,
        `exports.${bridge.preloadBindingName} = ${bridge.preloadBindingName};`,
      ];
    }),
    "",
  ].join("\n");
}

function renderLazyBridgeModule(moduleId: string, targetModuleId: string) {
  return [
    `goog.module(${JSON.stringify(moduleId)});`,
    `const __module = goog.require(${JSON.stringify(targetModuleId)});`,
    'for (const key in __module) {',
    '  if (key !== "default") {',
    "    exports[key] = __module[key];",
    "  }",
    "}",
    "exports.default = __module.default;",
    "",
  ].join("\n");
}

function dedupeLazyImports(lazyImports: LazyImport[]) {
  return [
    ...new Map(lazyImports.map((item) => [item.moduleId, item])).values(),
  ];
}

function applyChunkBridgesToResolvedChunks(
  chunkPlan: ClosureChunk[],
  bridgeFiles: Array<{ chunkName: string; filePath: string; moduleId: string }>,
) {
  const bridgesByChunk = new Map<string, typeof bridgeFiles>();
  for (const bridge of bridgeFiles) {
    const existing = bridgesByChunk.get(bridge.chunkName) ?? [];
    existing.push(bridge);
    bridgesByChunk.set(bridge.chunkName, existing);
  }
  for (const chunk of chunkPlan) {
    const bridges = bridgesByChunk.get(chunk.name) ?? [];
    if (bridges.length === 0) {
      continue;
    }
    chunk.files.push(...bridges.map((bridge) => bridge.filePath));
    chunk.entryPoints = bridges.map((bridge) => bridge.moduleId);
  }
}

function createChunkWrapper(chunk: ClosureChunk, wrapperNamespace: string) {
  const namespaceTarget = `globalThis.${wrapperNamespace}=globalThis.${wrapperNamespace}||{}`;
  if (chunk.kind === "base") {
    return `(function(${CHUNK_NAMESPACE}){%output%}).call(this,${namespaceTarget});`;
  }
  return `(function(${CHUNK_NAMESPACE}){var __gcc_manager=goog.module.ModuleManager.getInstance();__gcc_manager.beforeLoadModuleCode(${JSON.stringify(
    chunk.name,
  )});%output%__gcc_manager.setLoaded();}).call(this,${namespaceTarget});`;
}

function toChunkWrapperNamespace(baseChunkName: string) {
  const sanitized = baseChunkName.replace(/[^A-Za-z0-9_$]/g, "_");
  return `default_${sanitized}`;
}

function renderModuleInfoString(chunkPlan: ClosureChunk[]) {
  return chunkPlan
    .map((chunk) => {
      const dependencyIndexes = chunk.dependencies
        .map((dependency) =>
          chunkPlan.findIndex((candidate) => candidate.name === dependency),
        )
        .filter((index) => index >= 0)
        .map((index) => index.toString(36));
      return dependencyIndexes.length > 0
        ? `${chunk.name}:${dependencyIndexes.join(",")}`
        : chunk.name;
    })
    .join("/");
}

function resolveChunkPlan(
  chunkPlan: ChunkPlanChunk[],
  emittedOutDir: string,
): ClosureChunk[] {
  return chunkPlan.map((chunk) => ({
    dependencies: chunk.dependencies,
    entryPoints: chunk.entryFiles
      ? chunk.entryFiles.map((filePath) =>
          toGoogModuleId(
            path.join(emittedOutDir, filePath.replace(/\.[^/.]+$/, ".js")),
            emittedOutDir,
          ),
        )
      : (chunk.lazyModuleIds ?? []).length > 0
        ? [...(chunk.lazyModuleIds ?? [])]
      : chunk.files.length > 0
        ? [
            toGoogModuleId(
              path.join(
                emittedOutDir,
                chunk.files[chunk.files.length - 1].replace(/\.[^/.]+$/, ".js"),
              ),
              emittedOutDir,
            ),
          ]
        : [],
    files: chunk.files.map((filePath) =>
      path.join(emittedOutDir, filePath.replace(/\.[^/.]+$/, ".js")),
    ),
    kind: chunk.kind,
    lazyModuleIds: chunk.lazyModuleIds ?? [],
    name: chunk.name,
  }));
}

function getDefaultString(value: unknown): string | undefined {
  if (
    typeof value === "object" &&
    value !== null &&
    "default" in value &&
    typeof value.default === "string"
  ) {
    return value.default;
  }

  return undefined;
}

function uniquePaths(paths: string[]) {
  return [...new Set(paths)];
}

function toGoogModuleId(filePath: string, moduleRoot: string) {
  const relativePath = path.relative(moduleRoot, filePath).replace(/\\/g, "/");
  const withoutExtension = relativePath.replace(/\.[^/.]+$/, "");
  return `gcc.${withoutExtension
    .split("/")
    .map((segment) => segment.replace(/[^A-Za-z0-9_$]/g, "_"))
    .join(".")}`;
}

function resolveClosureCompilerJarPath(): string | undefined {
  const closureCompilerModule =
    closureCompilerPackage as ClosureCompilerPackageShape;
  const closureCompiler =
    closureCompilerPackage.compiler as ClosureCompilerClass;
  const jarPath =
    typeof closureCompiler.JAR_PATH === "string"
      ? closureCompiler.JAR_PATH
      : typeof closureCompilerModule.JAR_PATH === "string"
        ? closureCompilerModule.JAR_PATH
        : (getDefaultString(closureCompiler.JAR_PATH) ??
          getDefaultString(closureCompilerModule.JAR_PATH));

  return jarPath;
}

function configureClosureCompilerInstance(
  instance: ClosureCompilerInstance,
): ClosureCompilerInstance {
  const nativeImagePath = getNativeImagePath();
  if (nativeImagePath) {
    instance.JAR_PATH = null;
    instance.javaPath = nativeImagePath;
    return instance;
  }

  const jarPath = resolveClosureCompilerJarPath();
  if (jarPath) {
    instance.JAR_PATH = jarPath;
  }

  return instance;
}

async function runClosureCompiler(
  options: ClosureCompilerOptions,
): Promise<number> {
  const closureCompiler =
    closureCompilerPackage.compiler as ClosureCompilerClass;

  return new Promise((resolve) => {
    const compilerProcess = configureClosureCompilerInstance(
      new closureCompiler(options),
    );
    compilerProcess.run((exitCode, stdOut, stdErr) => {
      if (stdOut) {
        console.log(stdOut);
      }
      if (stdErr) {
        console.error(stdErr);
      }
      resolve(exitCode);
    });
  });
}

async function collectJavaScriptFiles(dir: string): Promise<string[]> {
  const files: string[] = [];
  const pending = [dir];

  while (pending.length > 0) {
    const currentDir = pending.pop()!;
    const entries = await fs.readdir(currentDir, { withFileTypes: true });
    for (const entry of entries) {
      const entryPath = path.join(currentDir, entry.name);
      if (entry.isDirectory()) {
        pending.push(entryPath);
        continue;
      }

      if (entry.name.endsWith(".js")) {
        files.push(entryPath);
      }
    }
  }

  files.sort((left, right) => left.localeCompare(right));
  return files;
}

async function collectClosureLibFiles(
  packageRoot: string,
  candidateFiles: string[],
): Promise<string[]> {
  const closureLibDir = path.join(packageRoot, "closure-lib");
  const cacheKey = `${closureLibDir}\0${await hashClosureLibSelection(candidateFiles)}`;
  const existing = closureLibFilesCache.get(cacheKey);
  if (existing) {
    return existing;
  }

  const filesPromise = selectClosureLibFiles(closureLibDir, candidateFiles);
  closureLibFilesCache.set(cacheKey, filesPromise);
  return filesPromise;
}

async function hashClosureLibSelection(filePaths: string[]) {
  const stats = await Promise.all(
    uniquePaths(filePaths).map(async (filePath) => {
      try {
        const stat = await fs.stat(filePath);
        return `${filePath}:${stat.size}:${stat.mtimeMs}`;
      } catch {
        return `${filePath}:missing`;
      }
    }),
  );
  return stats.sort((left, right) => left.localeCompare(right)).join("|");
}

async function selectClosureLibFiles(
  closureLibDir: string,
  candidateFiles: string[],
) {
  const usesChunkLoader = candidateFiles.some((filePath) =>
    filePath.includes(`${path.sep}__gcc_chunk_support${path.sep}`),
  );
  if (usesChunkLoader) {
    const vendoredLoaderFiles = await collectJavaScriptFiles(
      path.join(closureLibDir, "goog"),
    );
    return uniquePaths([path.join(closureLibDir, "base.js"), ...vendoredLoaderFiles]);
  }

  const required = [path.join(closureLibDir, "base.js")];
  const contents = (
    await Promise.all(
      uniquePaths(candidateFiles).map((filePath) =>
        fs.readFile(filePath, "utf-8").catch(() => ""),
      ),
    )
  ).join("\n");
  if (contents.includes("goog.reflect.")) {
    required.push(path.join(closureLibDir, "reflect.js"));
  }
  if (contents.includes("tslib")) {
    required.push(path.join(closureLibDir, "tslib.js"));
  }
  return required;
}
