/** @externs */
// Generated by gcc-ts-bundler for: jquery
// Mode: runtime-aware
// Scanned 6 type files and 1 runtime file.

Object.prototype.__className__;
Object.prototype.catch;
Object.prototype.click;
Object.prototype.display;
Object.prototype.events;
Object.prototype.expand;
Object.prototype.finish;
Object.prototype.fxshow;
Object.prototype.get;
Object.prototype.globalEval;
Object.prototype.handle;
Object.prototype.hasDataAttrs;
Object.prototype.height;
Object.prototype.set;
Object.prototype.value;
