import fs from "node:fs/promises";
import path from "node:path";

import type { ExternBarrierWarning } from "./types";

/**
 * Everything Closure treats as an extern *property* — i.e. a name removed from
 * `RenameProperties`' candidate set and from `DisambiguateProperties`'
 * partition, program-wide, for every owner type.
 *
 * There are three syntactic shapes and they are the same thing to the compiler:
 *
 * 1. `Object.prototype.X;` / `Function.prototype["X"];` — the flat barrier the
 *    rename-barrier artifacts emit.
 * 2. `Owner.prototype.X;` — an owner-qualified declaration. Still pins `X`
 *    globally for renaming; it only buys back *disambiguation*, and only on
 *    jobs that run type inference.
 * 3. `{"X": <type>}` — a record-literal key inside a type annotation. Typed
 *    declarations are full of these, and until this module existed they were
 *    counted nowhere: `GenerateExternsResult.renameBarriers.propertyNames`
 *    scanned the barrier text only, so a `typedOutputFile` could contribute an
 *    unbounded, unreported barrier set.
 *
 * All three are collected here so that one number describes what an artifact
 * actually costs.
 */

/** Names that appear in every extern file and are not app-visible barriers. */
const STRUCTURAL_NAMES = new Set(["prototype", "constructor"]);

const FLAT_BARRIER =
  /\b(?:Object|Function)\.prototype(?:\.([A-Za-z_$][\w$]*)|\[\s*"((?:[^"\\]|\\.)*)"\s*\])/gu;
const OWNER_BARRIER =
  /\b([A-Za-z_$][\w$.]*)\.prototype(?:\.([A-Za-z_$][\w$]*)|\[\s*"((?:[^"\\]|\\.)*)"\s*\])/gu;
const RECORD_KEY = /"((?:[^"\\]|\\.)*)"\s*:/gu;

export type BarrierKind = "flat" | "owner" | "record";

export interface BarrierName {
  kind: BarrierKind;
  /** Owner expression for `kind === "owner"`, otherwise undefined. */
  owner?: string | undefined;
  property: string;
}

/** Unescapes a quoted extern key (`Object.prototype["a\\u0062"]`). */
function decode(raw: string) {
  try {
    const value: unknown = JSON.parse(`"${raw}"`);
    return typeof value === "string" ? value : raw;
  } catch {
    return raw;
  }
}

/**
 * Every property name an extern source contributes to Closure's extern property
 * set, tagged by the shape it came from.
 *
 * Comment lines are stripped first: generated artifacts carry provenance
 * headers (`// Generated by gcc-ts-bundler for: react, react-dom`) that would
 * otherwise be scanned for record keys.
 */
export function collectBarrierNames(text: string): BarrierName[] {
  const source = stripComments(text);
  const found: BarrierName[] = [];
  const seen = new Set<string>();

  const push = (kind: BarrierKind, property: string, owner?: string) => {
    if (!property || STRUCTURAL_NAMES.has(property)) return;
    const key = `${kind}\u0000${owner ?? ""}\u0000${property}`;
    if (seen.has(key)) return;
    seen.add(key);
    found.push(owner ? { kind, owner, property } : { kind, property });
  };

  for (const match of source.matchAll(FLAT_BARRIER)) {
    push("flat", match[1] ?? decode(match[2] ?? ""));
  }
  for (const match of source.matchAll(OWNER_BARRIER)) {
    const owner = match[1] ?? "";
    if (owner === "Object" || owner === "Function") continue;
    push("owner", match[2] ?? decode(match[3] ?? ""), owner);
  }
  for (const match of source.matchAll(RECORD_KEY)) {
    push("record", decode(match[1] ?? ""));
  }

  return found;
}

/** Distinct property names an extern source pins, across all three shapes. */
export function collectBarrierPropertyNames(text: string): string[] {
  return [
    ...new Set(collectBarrierNames(text).map((barrier) => barrier.property)),
  ].sort();
}

/**
 * `Object.prototype.<name>;`, or the quoted form when the name is not a bare
 * JavaScript identifier. The single implementation — `contracts/usage.ts` used
 * to carry a byte-identical private copy.
 */
export function renderStructuralExternLine(name: string) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/u.test(name)
    ? `Object.prototype.${name};`
    : `Object.prototype[${JSON.stringify(name)}];`;
}

/**
 * Only `//` lines are dropped. Block comments must survive: in an externs
 * file the JSDoc block *is* the type annotation, so `/** @type {{"x": …}} *\/`
 * is where record-key barriers live. Stripping them would make the typed
 * artifact look free again — the exact blind spot this module exists to close.
 */
function stripComments(text: string) {
  return text.replace(/(^|[^:])\/\/[^\n]*/gu, "$1");
}

/**
 * Barrier counts stay non-fatal on purpose: a big barrier set is a *cost*
 * signal, not a correctness failure, and the only honest response is to show
 * the number and where it came from.
 */
export const BARRIER_WARNING_THRESHOLD = 200;

export interface BarrierSource {
  /** Declaration files that fed this artifact, for package attribution. */
  contributingFiles?: readonly string[] | undefined;
  label: string;
  text: string;
}

export interface BarrierAccounting {
  byKind: ReadonlyMap<BarrierKind, number>;
  label: string;
  propertyNames: string[];
  /** `package -> declaration files scanned`, biggest first. */
  topPackages: Array<{ files: number; name: string }>;
  total: number;
}

export function accountBarriers(source: BarrierSource): BarrierAccounting {
  const barriers = collectBarrierNames(source.text);
  const byKind = new Map<BarrierKind, number>([
    ["flat", 0],
    ["owner", 0],
    ["record", 0],
  ]);
  for (const barrier of barriers) {
    byKind.set(barrier.kind, (byKind.get(barrier.kind) ?? 0) + 1);
  }
  return {
    byKind,
    label: source.label,
    propertyNames: [
      ...new Set(barriers.map((barrier) => barrier.property)),
    ].sort(),
    topPackages: rankPackages(source.contributingFiles ?? []),
    total: new Set(barriers.map((barrier) => barrier.property)).size,
  };
}

/**
 * Warning text for an artifact over the threshold, or null. Names the top
 * contributing declaration packages so the number is actionable: "2,964
 * barriers" is noise, "2,964 barriers, mostly from @types/react" is a decision.
 */
export function formatBarrierWarning(
  accounting: BarrierAccounting,
  threshold = BARRIER_WARNING_THRESHOLD,
): string | null {
  if (accounting.total <= threshold) return null;
  const shape = (["flat", "owner", "record"] as const)
    .filter((kind) => (accounting.byKind.get(kind) ?? 0) > 0)
    .map((kind) => `${kind}=${accounting.byKind.get(kind) ?? 0}`)
    .join(" ");
  const packages = accounting.topPackages
    .slice(0, 5)
    .map((entry) => `${entry.name} (${entry.files})`)
    .join(", ");
  return (
    `${accounting.label} pins ${accounting.total} property names program-wide ` +
    `(${shape}). Every one is removed from Closure's renaming and ` +
    `disambiguation candidates for all owner types, not just the declaring ` +
    `package.` +
    (packages ? ` Top declaration packages: ${packages}.` : "") +
    ` Narrow the module list, set includeDependencies: false, or move to ` +
    `mode: "runtime-aware".`
  );
}

function rankPackages(files: readonly string[]) {
  const counts = new Map<string, number>();
  for (const file of files) {
    const name = packageNameForFile(file);
    if (name) counts.set(name, (counts.get(name) ?? 0) + 1);
  }
  return [...counts]
    .map(([name, count]) => ({ files: count, name }))
    .sort(
      (left, right) =>
        right.files - left.files || left.name.localeCompare(right.name),
    );
}

/**
 * Barrier audit for extern files handed to `build({ externs })`. Hand-written
 * extern files never pass through `generateExterns`, so nothing counted them
 * before; a checked-in 761-line `Object.prototype.*` file was invisible.
 *
 * Unreadable paths are skipped: the build reports missing externs itself, and
 * a cost signal must never be the thing that fails a build.
 */
export async function auditExternFiles(
  externFiles: readonly string[],
  projectRoot = process.cwd(),
): Promise<ExternBarrierWarning[]> {
  const warnings: ExternBarrierWarning[] = [];
  for (const externFile of externFiles) {
    const resolved = path.resolve(projectRoot, externFile);
    let text: string;
    try {
      text = await fs.readFile(resolved, "utf8");
    } catch {
      continue;
    }
    const accounting = accountBarriers({
      contributingFiles: [resolved],
      label: `extern file ${path.relative(projectRoot, resolved) || resolved}`,
      text,
    });
    const message = formatBarrierWarning(accounting);
    if (message) {
      warnings.push({
        artifact: accounting.label,
        message,
        propertyCount: accounting.total,
      });
    }
  }
  return warnings;
}

function packageNameForFile(filePath: string) {
  const parts = path.resolve(filePath).split(path.sep);
  const index = parts.lastIndexOf("node_modules");
  if (index === -1 || index + 1 >= parts.length) return null;
  const first = parts[index + 1];
  if (!first) return null;
  return first.startsWith("@") && parts[index + 2]
    ? `${first}/${parts[index + 2]}`
    : first;
}
