import type { ExternAnalysisContext } from "./context";
import { analyzeRuntimeUsage } from "./runtime-analysis";
import {
  collectBoundaryAwareExternLines,
  collectBoundaryAwareUsageMemberNames,
  collectCandidateExternLines,
} from "./contracts";
import { renderStructuralExternLine } from "./shared";

/** Extern lines for runtime protocol members plus used defined members. */
export function collectRuntimeUsageExternLines(
  runtimeUsage: {
    accessedMembers: ReadonlySet<string>;
    definedMembers: Iterable<string>;
    protocolMembers: Iterable<string>;
  },
  appUsageMembers: ReadonlySet<string>,
): Set<string> {
  const emittedLines = new Set<string>();
  for (const member of runtimeUsage.protocolMembers) {
    emittedLines.add(renderStructuralExternLine(member));
  }
  for (const member of runtimeUsage.definedMembers) {
    if (
      runtimeUsage.accessedMembers.has(member) ||
      appUsageMembers.has(member)
    ) {
      emittedLines.add(renderStructuralExternLine(member));
    }
  }
  return emittedLines;
}

type GenerateExternsMode = "boundary-aware" | "candidates" | "runtime-aware";

export function renderCandidateExterns({
  analysis,
  modules,
}: {
  analysis: ExternAnalysisContext;
  modules: string[];
}) {
  return renderExternText({
    emittedLines: collectCandidateExternLines(analysis.registry),
    mode: "candidates",
    modules,
    scannedFiles: analysis.scannedFiles,
  });
}

export function renderBoundaryAwareExterns({
  analysis,
  modules,
}: {
  analysis: ExternAnalysisContext;
  modules: string[];
}) {
  return renderExternText({
    emittedLines: collectBoundaryAwareExternLines(analysis),
    mode: "boundary-aware",
    modules,
    scannedFiles: analysis.scannedFiles,
  });
}

export async function renderRuntimeAwareExterns({
  analysis,
  modules,
  runtimeEntryFiles,
}: {
  analysis: ExternAnalysisContext;
  modules: string[];
  runtimeEntryFiles: string[];
}) {
  const appUsageMembers =
    analysis.appEntryFiles.length > 0
      ? collectBoundaryAwareUsageMemberNames(analysis)
      : new Set<string>();
  const runtimeUsage = await analyzeRuntimeUsage(runtimeEntryFiles);
  const emittedLines = collectRuntimeUsageExternLines(
    runtimeUsage,
    appUsageMembers,
  );

  return renderExternText({
    emittedLines,
    mode: "runtime-aware",
    modules,
    runtimeEntryFiles,
    scannedFiles: analysis.scannedFiles,
  });
}

function renderExternText({
  emittedLines,
  mode,
  modules,
  runtimeEntryFiles = [],
  scannedFiles,
}: {
  emittedLines: Set<string>;
  mode: GenerateExternsMode;
  modules: string[];
  runtimeEntryFiles?: string[];
  scannedFiles: string[];
}) {
  const scannedSummary =
    mode === "runtime-aware"
      ? `// Scanned ${scannedFiles.length} type file${scannedFiles.length === 1 ? "" : "s"} and ${runtimeEntryFiles.length} runtime file${runtimeEntryFiles.length === 1 ? "" : "s"}.`
      : `// Scanned ${scannedFiles.length} type file${scannedFiles.length === 1 ? "" : "s"}.`;

  return [
    "/** @externs */",
    `// Generated by gcc-ts-bundler for: ${modules.join(", ")}`,
    `// Mode: ${mode}`,
    scannedSummary,
    "",
    ...[...emittedLines].sort((left, right) => left.localeCompare(right)),
    "",
  ].join("\n");
}
