import type { ExternAnalysisContext } from "./context";
import { analyzeRuntimeUsage } from "./runtime-analysis";
import {
  collectBoundaryAwareExternLines,
  collectBoundaryAwareUsageMemberNames,
  collectCandidateExternLines,
} from "./contracts";
import { renderStructuralExternLine } from "./shared";

/** How the app reads members, split by the syntax Closure sees. */
export interface AppUsageMembers {
  dotAccessed: ReadonlySet<string>;
  stringLiteralRead: ReadonlySet<string>;
}

export function createEmptyAppUsageMembers(): AppUsageMembers {
  return { dotAccessed: new Set(), stringLiteralRead: new Set() };
}

/**
 * Extern lines for runtime protocol members plus genuinely mixed definition /
 * read pairs:
 *
 * ```
 * extern = protocolMembers
 *        ∪ (stringDefined ∩ dotAccessed)
 *        ∪ (dotDefined    ∩ stringLiteralRead)
 * ```
 *
 * A member that is dot-defined *and* dot-accessed renames consistently inside
 * one Closure invocation and must NOT be externed — externing it (and the
 * native property quoting an extern drives) is what previously neutralised
 * typed-annotation optimisation on ordinary app domain fields.
 */
export function collectRuntimeUsageExternLines(
  runtimeUsage: {
    dotAccessed: ReadonlySet<string>;
    dotDefined: Iterable<string>;
    protocolMembers: Iterable<string>;
    stringDefined: Iterable<string>;
    stringLiteralRead: ReadonlySet<string>;
  },
  appUsage: AppUsageMembers,
): Set<string> {
  const emittedLines = new Set<string>();
  for (const member of runtimeUsage.protocolMembers) {
    emittedLines.add(renderStructuralExternLine(member));
  }
  for (const member of runtimeUsage.stringDefined) {
    if (
      runtimeUsage.dotAccessed.has(member) ||
      appUsage.dotAccessed.has(member)
    ) {
      emittedLines.add(renderStructuralExternLine(member));
    }
  }
  for (const member of runtimeUsage.dotDefined) {
    if (
      runtimeUsage.stringLiteralRead.has(member) ||
      appUsage.stringLiteralRead.has(member)
    ) {
      emittedLines.add(renderStructuralExternLine(member));
    }
  }
  return emittedLines;
}

type GenerateExternsMode = "boundary-aware" | "candidates" | "runtime-aware";

export function renderCandidateExterns({
  analysis,
  modules,
}: {
  analysis: ExternAnalysisContext;
  modules: string[];
}) {
  return renderExternText({
    emittedLines: collectCandidateExternLines(analysis.registry),
    mode: "candidates",
    modules,
    scannedFiles: analysis.scannedFiles,
  });
}

export function renderBoundaryAwareExterns({
  analysis,
  modules,
}: {
  analysis: ExternAnalysisContext;
  modules: string[];
}) {
  return renderExternText({
    emittedLines: collectBoundaryAwareExternLines(analysis),
    mode: "boundary-aware",
    modules,
    scannedFiles: analysis.scannedFiles,
  });
}

export async function renderRuntimeAwareExterns({
  analysis,
  modules,
  protocolHelpers,
  runtimeEntryFiles,
}: {
  analysis: ExternAnalysisContext;
  modules: string[];
  protocolHelpers: {
    keyExclusionListCallees: string[];
    keyReadCallees: string[];
  };
  runtimeEntryFiles: string[];
}) {
  // Boundary-aware usage is type-derived: members the app reaches through a
  // contract, which it always spells as a dot access.
  const appUsage: AppUsageMembers =
    analysis.appEntryFiles.length > 0
      ? {
          dotAccessed: collectBoundaryAwareUsageMemberNames(analysis),
          stringLiteralRead: new Set<string>(),
        }
      : createEmptyAppUsageMembers();
  const runtimeUsage = await analyzeRuntimeUsage(
    runtimeEntryFiles,
    protocolHelpers,
  );
  const emittedLines = collectRuntimeUsageExternLines(runtimeUsage, appUsage);

  return renderExternText({
    emittedLines,
    mode: "runtime-aware",
    modules,
    runtimeEntryFiles,
    scannedFiles: analysis.scannedFiles,
  });
}

function renderExternText({
  emittedLines,
  mode,
  modules,
  runtimeEntryFiles = [],
  scannedFiles,
}: {
  emittedLines: Set<string>;
  mode: GenerateExternsMode;
  modules: string[];
  runtimeEntryFiles?: string[];
  scannedFiles: string[];
}) {
  const scannedSummary =
    mode === "runtime-aware"
      ? `// Scanned ${scannedFiles.length} type file${scannedFiles.length === 1 ? "" : "s"} and ${runtimeEntryFiles.length} runtime file${runtimeEntryFiles.length === 1 ? "" : "s"}.`
      : `// Scanned ${scannedFiles.length} type file${scannedFiles.length === 1 ? "" : "s"}.`;

  return [
    "/** @externs */",
    `// Generated by gcc-ts-bundler for: ${modules.join(", ")}`,
    `// Mode: ${mode}`,
    scannedSummary,
    "",
    ...[...emittedLines].sort((left, right) => left.localeCompare(right)),
    "",
  ].join("\n");
}
