/** @externs */
// Generated by gcc-ts-bundler for: jquery
// Mode: runtime-aware
// Scanned 6 type files and 1 runtime file.

Object.prototype.__className__;
Object.prototype._queueHooks;
Object.prototype.catch;
Object.prototype.click;
Object.prototype.dequeue;
Object.prototype.display;
Object.prototype.events;
Object.prototype.expand;
Object.prototype.finish;
Object.prototype.fireWith;
Object.prototype.fxshow;
Object.prototype.get;
Object.prototype.globalEval;
Object.prototype.handle;
Object.prototype.hasDataAttrs;
Object.prototype.height;
Object.prototype.innerHTML;
Object.prototype.marginLeft;
Object.prototype.notifyWith;
Object.prototype.offsetHeight;
Object.prototype.offsetParent;
Object.prototype.offsetWidth;
Object.prototype.rejectWith;
Object.prototype.replaceWith;
Object.prototype.resolveWith;
Object.prototype.scrollboxSize;
Object.prototype.scrollLeft;
Object.prototype.scrollTo;
Object.prototype.scrollTop;
Object.prototype.set;
Object.prototype.swing;
Object.prototype.value;
