/** @externs */
// Generated by gcc-ts-bundler for: jquery
// Mode: boundary-aware
// Scanned 6 type files.

Object.prototype.addClass;
Object.prototype.always;
Object.prototype.animate;
Object.prototype.append;
Object.prototype.attr;
Object.prototype.closest;
Object.prototype.css;
Object.prototype.data;
Object.prototype.Deferred;
Object.prototype.done;
Object.prototype.each;
Object.prototype.fadeIn;
Object.prototype.fadeOut;
Object.prototype.fail;
Object.prototype.find;
Object.prototype.hasClass;
Object.prototype.key;
Object.prototype.length;
Object.prototype.on;
Object.prototype.promise;
Object.prototype.prop;
Object.prototype.queue;
Object.prototype.reject;
Object.prototype.remove;
Object.prototype.removeClass;
Object.prototype.resolve;
Object.prototype.stop;
Object.prototype.text;
Object.prototype.toggleClass;
Object.prototype.trigger;
Object.prototype.val;
Object.prototype.when;
