[package]
name = "gcc_ts_bundler_native"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2.16.13", default-features = false, features = ["napi8"] }
napi-derive = "2.16.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
swc_core = { version = "59.0.1", features = ["common", "ecma_ast", "ecma_codegen", "ecma_parser", "ecma_visit"] }
swc_ecma_transforms_base = "39.0.0"
swc_ecma_transforms_module = "43.0.0"
swc_ecma_transforms_typescript = "43.0.0"

[build-dependencies]
napi-build = "2.1.5"
