import ts from "typescript";

import { analyzeRuntimeUsage } from "./runtime-analysis";
import {
  collectBoundaryAwareExternLines,
  collectCandidateExternLines,
} from "./contracts";
import { ContractRegistry, renderStructuralExternLine } from "./shared";

type GenerateExternsMode = "boundary-aware" | "candidates" | "runtime-aware";

export function renderCandidateExterns({
  modules,
  registry,
  scannedFiles,
}: {
  modules: string[];
  registry: ContractRegistry;
  scannedFiles: string[];
}) {
  return renderExternText({
    emittedLines: collectCandidateExternLines(registry),
    mode: "candidates",
    modules,
    scannedFiles,
  });
}

export function renderBoundaryAwareExterns({
  appEntryFiles,
  compilerOptions,
  modules,
  projectRoot,
  registry,
  scannedFiles,
}: {
  appEntryFiles: string[];
  compilerOptions: ts.CompilerOptions;
  modules: string[];
  projectRoot: string;
  registry: ContractRegistry;
  scannedFiles: string[];
}) {
  return renderExternText({
    emittedLines: collectBoundaryAwareExternLines({
      appEntryFiles,
      compilerOptions,
      projectRoot,
      registry,
    }),
    mode: "boundary-aware",
    modules,
    scannedFiles,
  });
}

export async function renderRuntimeAwareExterns({
  appEntryFiles,
  compilerOptions,
  modules,
  projectRoot,
  registry,
  runtimeEntryFiles,
  scannedFiles,
}: {
  appEntryFiles: string[];
  compilerOptions: ts.CompilerOptions;
  modules: string[];
  projectRoot: string;
  registry: ContractRegistry;
  runtimeEntryFiles: string[];
  scannedFiles: string[];
}) {
  const emittedLines =
    appEntryFiles.length > 0
      ? collectBoundaryAwareExternLines({
          appEntryFiles,
          compilerOptions,
          projectRoot,
          registry,
        })
      : collectCandidateExternLines(registry);
  const runtimeMembers = await analyzeRuntimeUsage(runtimeEntryFiles);
  for (const member of runtimeMembers) {
    emittedLines.add(renderStructuralExternLine(member));
  }

  return renderExternText({
    emittedLines,
    mode: "runtime-aware",
    modules,
    runtimeEntryFiles,
    scannedFiles,
  });
}

function renderExternText({
  emittedLines,
  mode,
  modules,
  runtimeEntryFiles = [],
  scannedFiles,
}: {
  emittedLines: Set<string>;
  mode: GenerateExternsMode;
  modules: string[];
  runtimeEntryFiles?: string[];
  scannedFiles: string[];
}) {
  const scannedSummary =
    mode === "runtime-aware"
      ? `// Scanned ${scannedFiles.length} type file${scannedFiles.length === 1 ? "" : "s"} and ${runtimeEntryFiles.length} runtime file${runtimeEntryFiles.length === 1 ? "" : "s"}.`
      : `// Scanned ${scannedFiles.length} type file${scannedFiles.length === 1 ? "" : "s"}.`;

  return [
    "/** @externs */",
    `// Generated by gcc-ts-bundler for: ${modules.join(", ")}`,
    `// Mode: ${mode}`,
    scannedSummary,
    "",
    ...[...emittedLines].sort((left, right) => left.localeCompare(right)),
    "",
  ].join("\n");
}
